# Generated by Django 2.0.9 on 2019-01-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='image',
            field=models.ForeignKey(default='Image', on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
